#!/bin/bash
# weather
# Fetch the local weather
# Author: <eindira@promptu.com>
# Usage:    weather [--oz] [--temp | -t]
#
# Args: none: Print today's weather in MP
#       --loc || -l <LOCATION>: Print the weather near <LOCATION>
#
#       <LOCATION> may be any of the following:
#       {OZ, BR, SY, LA, SF, MP, SL, CH, NY, DC,
#        AM, LO, TO, KL, NO, IS, BJ, HK, MO, PR, 
#        PA, BE}
#
#       Type 'weather --cities' for more information
#
#       --temp || -t: Return only the temp
#       --full || -f || --week || -w: Show the full week's weather
#       --help || -h: Print this message and exit

#Init variables to hold flag values
TEMP=false
LOCATION=""
LOCATION_STRING=""
WEEK=false
UNITS="?u"
VERBOSE=true
ART=true
while [[ $# -gt 0 ]]
do
    key="$1"
    case $key in
        --help|-h)
            # Print usage infor when a help flag is used
            # Once printed, exit
            printf "\nUsage:\tweather [--oz] [--temp | -t]\n\n"
            printf "Args:\tnone: Print today's weather in MP\n" # TODO Update to reflect loc changes
            printf "\t--loc || -l || in <LOCATION>: Print the weather near <LOCATION>\n"
            printf "\n\t<LOCATION> may be any of the following:\n"
            printf "\t{OZ, BR, SY, LA, SF, MP, SL, CH, NY, DC,"
            printf "\n\t AM, LO, TO, KL, NO, IS, BJ, HK, MO, PR,"
            printf "\n\t PA, BE}\n\n"
            printf "\tType 'weather --cities' for more information\n\n"
            printf "\t--temp || -t: Return only the temp\n"
            printf "\t--full || -f || --week || -w: Show the full week's weather\n"
            printf "\t--less_verbose || -lv: Minimal verbosity in output\n"
            printf "\t--no_art || -na: Print without ASCII art\n"
            printf "\t--help || -h: Print this message and exit\n\n"
            exit 0
            ;;
        --cities)
            printf "weather -- Available Cities\n"
            printf "===========================\n"
            printf "The available cities are:\n"
            printf "\tOZ:Queensland, BR:Brisbane, SY:Sydney, LA:LA, SF:San Francisco\n"
            printf "\tMP:Menlo Park, SL: Salt Lake City, CH:Chicago, NY:New York, DC:Washington DC\n"
            printf "\tAM:Amsterdam, LO:London, TO:Tokyo, KL:Kuala Lumpur, NO:Novokuznetsk, IS:Istanbul\n"
            printf "\tBJ:Beijing, HK:Hong Kong, MO:Moscow, PR:Prague, PA:Paris, BE:Berlin\n"
            exit 0
            ;;
        --loc|-l)
            # Set location argument to the two letter code given immediately after
            shift
            LOCATION="$1"
            ;;
        --temp|-t)
            # Set TEMP to true
            TEMP=true
            ;;
        --full|-f|--week|-w)
            # Set WEEK to true
            WEEK=true
            ;;
        --metric|-m|--celsius|-c)
            # Set displayed units to metric/celsius
            UNITS="?m"
            ;;
        --less_verbose|-lv)
            # Mimimize printed output
            VERBOSE=false
            ;;
        --no_art|-na)
            # No ASCII art
            # An option for those without an appreciation for the finer things
            ART=false
            ;;
        *)
            # Unkown option
            printf "Unknown Option: \"%s\"\n" "$key"
            ;;
    esac
    shift
done

LOC_URL=""

if [ "$LOCATION" = "" ] ; then
    LOC_URL="wttr.in/menlo_park"
    LOCATION="MP"
    LOCATION_STRING="Menlo Park, California"
else
    case $LOCATION in
        # Australia
        OZ)
            LOC_URL="wttr.in/gold_coast"
            LOCATION_STRING="Gold Coast, Australia"
            ;;
        GC|Gold_Coast)
            LOC_URL="wttr.in/gold_coast"
            LOCATION_STRING="Gold Coast, Australia"
            LOCATION="OZ"
            ;;
        BR|Brisbane)
            LOC_URL="wttr.in/brisbane"
            LOCATION_STRING="Brisbane, Australia"
            ;;
        SY|Sydney)
            LOC_URL="wttr.in/sydney"
            LOCATION_STRING="Sydney, Australia"
            ;;
        # California
        LA|Los_Angeles)
            LOC_URL="wttr.in/los_angeles"
            LOCATION_STRING="Los Angeles, California"
            ;;
        SF|San_Francisco)
            LOC_URL="wttr.in/sf"
            LOCATION_STRING="San Francisco, California"
            ;;
        BK|Berkeley)
            LOC_URL="wttr.in/berkeley"
            LOCATION_STRING="Berkeley, California"
            ;;
        OAK|Oakland)
            LOC_URL="wttr.in/oakland"
            LOCATION_STRING="Oakland, California"
            ;;
        SJ|San_Jose)
            LOC_URL="wttr.in/san_jose"
            LOCATION_STRING="San Jose, California"
            ;;
        MP|Menlo_Park)
            LOC_URL="wttr.in/menlo_park"
            LOCATION_STRING="Menlo Park, California"
            ;;
        TR|Torrance)
            LOC_URL="wttr.in/torrance"
            LOCATION_STRING="Torrance, California"
            ;;
        SD|San_Diego)
            LOC_URL="wttr.in/san_diego"
            LOCATION_STRING="San Diego, California"
            ;;
        VTA|Ventura)
            LOC_URL="wttr.in/ventura"
            LOCATION_STRING="Ventura, California"
            ;;
        SB|Santa_Barbara)
            LOC_URL="wttr.in/santa_barbara"
            LOCATION_STRING="Santa_Barbara, California"
            ;;
        OJ|Ojai)
            LOC_URL="wttr.in/ojai_california"
            LOCATION_STRING="Ojai, California"
            ;;
        # Rest of US
        SL|SLC|Salt_Lake_City)
            LOC_URL="wttr.in/salt_lake_city"
            LOCATION_STRING="Salt Lake City, Utah"
            ;;
        DE|Denver)
            LOC_URL="wttr.in/denver"
            LOCATION_STRING="Denver, Colorado"
            ;;
        CH|Chicago)
            LOC_URL="wttr.in/chicago"
            LOCATION_STRING="Chicago, Illinois"
            ;;
        NY|New_York)
            LOC_URL="wttr.in/new_york"
            LOCATION_STRING="New York, New York"
            ;;
        DC|Washington_DC)
            LOC_URL="wttr.in/washington_dc"
            LOCATION_STRING="Washington DC"
            ;;
        SEA|Seattle)
            LOC_URL="wttr.in/seattle"
            LOCATION_STRING="Seattle, Washinton"
            ;;
        PDX|Portland)
            LOC_URL="wttr.in/portland"
            LOCATION_STRING="Portland, Oregon"
            ;;
        DB|Daytona_Beach)
            LOC_URL="wttr.in/daytona_beach"
            LOCATION_STRING="Daytona Beach, Florida"
            ;;
        OR|Orlando)
            LOC_URL="wttr.in/orlando"
            LOCATION_STRING="Orlando, Florida"
            ;;
        MI|Miami)
            LOC_URL="wttr.in/miami"
            LOCATION_STRING="Miami, Florida"
            ;;
        # Europe
        AM|Amsterdam)
            LOC_URL="wttr.in/amsterdam"
            LOCATION_STRING="Amsterdam, Netherlands"
            ;;
        GL|Glasgow)
            LOC_URL="wttr.in/glasgow"
            LOCATION_STRING="Glasgow, United Kingdom"
            ;;
        LO|London)
            LOC_URL="wttr.in/london"
            LOCATION_STRING="London, UK"
            ;;
        PR|Prague)
            LOC_URL="wttr.in/prague"
            LOCATION_STRING="Prague, Czech Republic"
            ;;
        PA|Paris)
            LOC_URL="wttr.in/paris"
            LOCATION_STRING="Paris, France"
            ;;
        BE|Berlin)
            LOC_URL="wttr.in/berlin"
            LOCATION_STRING="Berlin, Germany"
            ;;
        # Russia
        MO|Moscow)
            LOC_URL="wttr.in/moscow"
            LOCATION_STRING="Moscow, Russia"
            ;;
        NB|Novosibirsk)
            LOC_URL="wttr.in/novosibirsk"
            LOCATION_STRING="Novosibirsk, Russia"
            ;;
        NO|Novokuznetsk)
            LOC_URL="wttr.in/novokuznetsk"
            LOCATION_STRING="Novokuznetsk, Russia"
            ;;
        # Asia
        IS|Istanbul)
            LOC_URL="wttr.in/istanbul"
            LOCATION_STRING="Istanbul, Turkey"
            ;;
        TO|Tokyo)
            LOC_URL="wttr.in/tokyo"
            LOCATION_STRING="Tokyo, Japan"
            ;;
        KL|Kuala_Lumpur)
            LOC_URL="wttr.in/kuala_lumpur"
            LOCATION_STRING="Kuala Lumpur, Malaysia"
            ;;
        SG|Singapore)
            LOC_URL="wtrr.in/singapore"
            LOCATION_STRING="Singapore, Singapore"
            ;;
        BJ|Beijing)
            LOC_URL="wttr.in/beijing"
            LOCATION_STRING="Beijing, China"
            ;;
        HK|Hongkong|Hong_Kong)
            LOC_URL="wttr.in/hong_kong"
            LOCATION_STRING="Hong Kong"
            ;;
        # Not yet a supported location
        *)
            LOCATION_URL_SLUG="$(echo "$LOCATION" | tr "[:upper:]" "[:lower:]" | sed 's/ /_/')"
            LOC_URL="wttr.in/$LOCATION_URL_SLUG"
            LOCATION_STRING="$LOCATION"
            ;;
    esac
fi

LOC_URL="$LOC_URL"+$UNITS

echo

if [ $ART = false ] ; then
    LOC_URL="$LOC_URL"+'0T' # Get a LOC_URL w/o terminal colors
    WEATHER_STR=$(curl -s -N "$LOC_URL" | tail -n 5)
    # shellcheck disable=SC2086
    # Suppress shellcheck false-positives while linting this particular line
    echo $WEATHER_STR | tr -d "[:punct:]" | awk -F'°' '{print $1 "°" substr($2, 0, 1)}'
    exit 0
fi

if [ $TEMP = true ] ; then
    curl -s -N "$LOC_URL" | grep "°" | head -n 1 | awk '{print $(NF-1) " " $NF}'
elif [ $VERBOSE = false ] ; then
    curl -s -N "$LOC_URL" | head -n 7 | tail -n 5
elif [ $WEEK = false ] ; then
    currenttime -l $LOCATION --date --dow
    echo "Location: $LOCATION_STRING"
    curl -s -N "$LOC_URL" | head -n 7 | tail -n +2
else
    curl -s -N "$LOC_URL" | head -n -2
fi

echo
