#!/bin/bash
# p4-size
# Prints the collective size of files in a p4 depot location
# Useful for determining how much you'll suffer if you blindly 'p4 sync ...' a directory
# Author: <eindiran@promptu.com>

SHORT=a
LONG=additional
PARSED=$(getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@")

if [[ $? -ne 0 ]]; then
    exit 2
fi

eval set -- "$PARSED"
while true; do
    case "$1" in
        -a|--additional)
            current_dir_size=$(/bin/ls -FaGl "${@}" | awk '{total+=$4;}; END {print total}')
            echo $current_dir_size
            p4_dir=$(p4 where | awk '{print $1}')
            p4_size=$(p4 sizes ... | awk '{my_byte_size+=$(NF-1)} END{print my_byte_size}')
            echo $p4_size
            additional_size=$((p4_size-current_dir_size))
            echo "$p4_dir	Additional files to download:$(echo $additional_size | numfmt --to=iec --suffix=B)"
            exit 1
            ;;
        --)
            p4_dir=$(p4 where | awk '{print $1}')
            p4_size=$(p4 sizes ... | awk '{my_byte_size+=$(NF-1)} END{print my_byte_size}' | numfmt --to=iec --suffix=B)
            echo "$p4_dir	$p4_size"
            exit 1
            ;;
        *)
            echo "Unrecognized option."
            echo "Usage: 'p4-size [-a | --additional]'"
            exit 3
            ;;
    esac
done

